import type { Clause, ContextPack, StoredCommittee } from "../types";
import { normalizeCommittee } from "./storage";

export interface MunPack {
  version: 1;
  type: "munpack";
  timestamp: number;
  packageId: string;
  sourceCountry: string;
  recipientCountry: string;
  perspective: "full-backup" | "recipient-pov";
  scenario: { committee: string; agenda: string; phase: string };
  committee: StoredCommittee;
}

export interface ImportResult {
  ok: boolean;
  kind: "full" | "munpack" | "context" | "text" | "invalid";
  committee?: StoredCommittee;
  context?: Partial<ContextPack>;
  message: string;
}

function isObject(v: unknown): v is Record<string, unknown> {
  return typeof v === "object" && v !== null && !Array.isArray(v);
}

export function validateCommitteeShape(data: unknown): data is StoredCommittee {
  if (!isObject(data)) return false;
  if (typeof data.id !== "string") return false;
  if (!isObject(data.contextPack)) return false;
  const ctx = data.contextPack as Record<string, unknown>;
  return typeof ctx.committee === "string"
    && typeof ctx.agenda === "string"
    && typeof ctx.country === "string"
    && Array.isArray(data.speeches)
    && Array.isArray(data.clauses)
    && Array.isArray(data.blocEntries);
}

export function validateMunPack(data: unknown): data is MunPack {
  if (!isObject(data)) return false;
  if (data.type !== "munpack" || data.version !== 1) return false;
  if (typeof data.packageId !== "string") return false;
  if (typeof data.sourceCountry !== "string" || typeof data.recipientCountry !== "string") return false;
  return validateCommitteeShape(data.committee);
}

export function exportCommitteeAsJSON(committee: StoredCommittee): string {
  return JSON.stringify({
    type: "mun-command-center-backup",
    version: 1,
    exportedAt: Date.now(),
    committee,
  }, null, 2);
}

export function importCommitteeFromJSON(json: string): StoredCommittee | null {
  try {
    const data = JSON.parse(json);
    if (isObject(data) && data.type === "mun-command-center-backup" && validateCommitteeShape(data.committee)) {
      return normalizeCommittee(data.committee);
    }
    if (validateCommitteeShape(data)) return normalizeCommittee(data);
    return null;
  } catch {
    return null;
  }
}

export function exportPOVPackage(committee: StoredCommittee, recipientCountry: string): string {
  const targetEntry = committee.blocEntries.find((e) => e.country.toLowerCase() === recipientCountry.toLowerCase());
  const ctx: ContextPack = {
    ...committee.contextPack,
    country: recipientCountry,
    role: "Delegate",
    bloc: targetEntry?.bloc || committee.contextPack.bloc,
    active_goal: `Represent ${recipientCountry}'s interests on ${committee.contextPack.agenda}`,
    next_action_needed: "Review imported scenario and confirm your position",
  };
  ctx.allies = committee.blocEntries.filter((e) => e.stance === "ally" && e.country !== recipientCountry).map((e) => e.country);
  ctx.opponents = committee.blocEntries.filter((e) => e.stance === "opponent" && e.country !== recipientCountry).map((e) => e.country);

  const publicClauses: Clause[] = committee.clauses.filter((c) => c.status !== "draft");
  const povCommittee: StoredCommittee = normalizeCommittee({
    ...committee,
    id: `munpack-${Date.now().toString(36)}`,
    contextPack: ctx,
    speeches: [],
    clauses: publicClauses,
    timeline: [
      {
        id: `import-marker-${Date.now().toString(36)}`,
        timestamp: Date.now(),
        type: "import",
        title: `Scenario imported for ${recipientCountry}`,
        description: `POV package generated by ${committee.contextPack.country}`,
        icon: "📦",
      },
      ...committee.timeline,
    ],
  });

  const pack: MunPack = {
    version: 1,
    type: "munpack",
    timestamp: Date.now(),
    packageId: `munpack-${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 7)}`,
    sourceCountry: committee.contextPack.country,
    recipientCountry,
    perspective: "recipient-pov",
    scenario: {
      committee: committee.contextPack.committee,
      agenda: committee.contextPack.agenda,
      phase: committee.contextPack.current_phase,
    },
    committee: povCommittee,
  };
  return JSON.stringify(pack, null, 2);
}

export function importPOVPackage(json: string): StoredCommittee | null {
  try {
    const data = JSON.parse(json);
    if (!validateMunPack(data)) return null;
    return normalizeCommittee(data.committee);
  } catch {
    return null;
  }
}

export function parseImportPayload(text: string): ImportResult {
  try {
    const data = JSON.parse(text);
    if (validateMunPack(data)) {
      return { ok: true, kind: "munpack", committee: normalizeCommittee(data.committee), message: `Valid POV package for ${data.recipientCountry}` };
    }
    const full = importCommitteeFromJSON(text);
    if (full) return { ok: true, kind: "full", committee: full, message: "Valid full backup" };
    return { ok: false, kind: "invalid", message: "JSON is valid but not a recognized MUN package or backup" };
  } catch {
    return { ok: true, kind: "text", message: "Plain text payload" };
  }
}

export function downloadAsFile(content: string, filename: string, type: string = "application/json"): void {
  const blob = new Blob([content], { type });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export function readFileAsText(file: File): Promise<string> {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onload = () => resolve(reader.result as string);
    reader.onerror = () => reject(reader.error);
    reader.readAsText(file);
  });
}

export async function copyToClipboard(text: string): Promise<boolean> {
  try {
    await navigator.clipboard.writeText(text);
    return true;
  } catch {
    const ta = document.createElement("textarea");
    ta.value = text;
    ta.style.position = "fixed";
    ta.style.left = "-9999px";
    document.body.appendChild(ta);
    ta.select();
    try {
      document.execCommand("copy");
      return true;
    } catch {
      return false;
    } finally {
      document.body.removeChild(ta);
    }
  }
}